name: Feature Request
description: Suggest an idea for this project.
title: "Feature Request | My Awesome Idea"
labels:
  - enhancement
projects:
  - funilrys/6
assignees:
  - funilrys
body:
  - type: markdown
    attributes:
      value: |+
        Thanks for taking the time to fill out this feature request!

        lease be patient and rest assured that we will get back to you as soon as possible.
        To help us understand and reproduce the issue, please provide as much information as possible.

        If you have a question or need help, please ask in our [Discussions](https://github.com/funilrys/PyFunceble/discussions) section.

  - type: textarea
    id: feature
    attributes:
      label: What is the feature you'd like to request?
      description: Please describe the feature you'd like to request.
      placeholder: |
        I'd like to request a feature that...
      value: |
        I'd like to request a feature that...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Please describe the problem you are trying to solve.
      placeholder: |
        I'm trying to solve a problem where...
      value: |
        I'm trying to solve a problem where...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What solution would you like to see?
      description: Please describe the solution you'd like to see.
      placeholder: |
        I'd like to see a solution that...
      value: |
        I'd like to see a solution that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Are there any alternatives you've considered?
      description: Please describe any alternatives you've considered.
      placeholder: |
        I've considered alternatives such as...
      value: |
        I've considered alternatives such as...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Please provide any additional context or screenshots.
      placeholder: |
        I would like to add...
      value: |
        I would like to add...
    validations:
      required: false

  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.org/todo).
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
